# Generated by Django 4.1.5 on 2023-01-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quotedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
