# Generated by Django 4.1.5 on 2023-01-10 09:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_body_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
