# Generated by Django 3.2 on 2022-11-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='date',
        ),
    ]
