# Generated by Django 4.0 on 2023-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='post',
            name='updatet_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
