# Generated by Django 3.2 on 2022-12-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20221202_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
