# Generated by Django 4.1.5 on 2023-01-07 13:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body_text',
            field=ckeditor.fields.RichTextField(verbose_name='Контент'),
        ),
    ]
